<?php

class Monkeyv4Controller extends RedirectController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionOnepay()
    {

    }
}