<div class="border-line">
    <span></span>
</div>
<div class="title">
    <span class="chicken"></span>
    <h2>Terms and conditions</h2>
</div>
<div class="clear"></div>

<div class="content">
    <p><strong style="font-size: 20px; color: black;">Monkey Junior Terms and Conditions&nbsp;("Agreement")</strong></p>
<p>Please read these Terms and Conditions ("Agreement", "Terms and Conditions") carefully before using www.monkeyjunior.com ("the App") operated by Early Start Co. Limited doing business as Monkey Junior ("us", "we", or "our"). This Agreement sets forth the legally binding terms and conditions for your use of the App at www.monkeyjunior.com.<br /> <br /> By accessing or using the App in any manner, including, but not limited to, visiting or browsing the App or contributing content or other materials to the App, you agree to be bound by these Terms and Conditions. Capitalized terms are defined in this Agreement.</p>
<p>These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Monkey Junior without restriction. Any attempted transfer or assignment in violation hereof shall be null and void.</p>
<p>NO WARRANTIES OF ANY KIND (INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE) ARE GIVEN WITH RESPECT TO THE PROPRIETARY INFORMATION DISCLOSED OR USED UNDER THIS AGREEMENT, AND NEITHER PARTY SHALL BE LIABLE TO THE OTHER DAMAGES ARISING OUT OF OR CAUSED BY DEFECTS OR DEFICIENCIES IN THE PROPRIETARY INFORMATION OF EITHER PARTY, WHETHER DIRECT, INCIDENTAL, CONSEQUENTIAL OR OTHERWISE.<br /> <br /> <strong style="font-size: 20px; color: black;">Intellectual Property</strong><br /> The App and its original content, graphic, images, videos, features and functionality are owned by Monkey Junior and are protected by international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>
<p><strong style="font-size: 20px; color: black;">Usage of the Service<br /></strong>The App offers comprehensive reading courses for babies, toddlers and preschoolers that teach your child to read, progressing from single words to phrases, from short sentences to very complicated ones. The App is developed in collaboration with early education experts and adopts the scientifically proven methodologies.</p>
<p>Monkey Junior does not endorse any User Submissions or any opinion, recommendation, or advice expressed therein, and we expressly disclaim any and all liability in connection with User Submissions. Monkey Junior does not permit copyright infringing activities and infringement of intellectual property rights via the App.</p>
<p>While using the App, you may encounter content that may be deemed offensive, indecent, or objectionable. Nevertheless, you agree to use our Service at your sole risk and we shall not have any liability to you for content that may be found to be offensive, indecent, or objectionable. You agree not to exploit the Service in any unauthorized way whatsoever, including but not limited to, trespassing or burdening network capacity.</p>
<p>Monkey Junior may automatically check your version of the Licensed Application with the sole intention of making the updated version available to you. Monkey Junior has no obligation to make available any updates. However, Monkey Junior may (a) require you to download and install updates; or (b) automatically download and install updates to your device.</p>
<p><strong style="font-size: 20px; color: black;">Termination</strong><br /> We may terminate your access to the App, without cause or notice, which may result in the forfeiture and destruction of all information associated with you. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.<br /> <br /> <strong style="font-size: 20px; color: black;">Links To Other Sites</strong><br /> Our Site may contain links to third-party sites that are not owned or controlled by Monkey Junior.<br /> Monkey Junior has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party sites or services. We strongly advise you to read the terms and conditions and privacy policy of any third-party site that you visit.<br /> <br /> <strong style="font-size: 20px; color: black;">Governing Law</strong><br /> This Agreement (and any further rules, policies, or guidelines incorporated by reference) shall be governed and construed in accordance with the laws of Vietnam without giving effect to any principles of conflicts of law.<br /> <br /> <strong style="font-size: 20px; color: black;">Changes To This Agreement</strong><br /> We reserve the right, at our sole discretion, to modify or replace these Terms and Conditions by posting the updated terms on the App. Your continued use of the App after any such changes constitutes your acceptance of the new Terms and Conditions.<br /> <br /> Please review this Agreement periodically for changes. If you do not agree to any of this Agreement or any changes to this Agreement, do not use, access or continue to access the App or discontinue any use of the App immediately.<br /> <br /> If you have any questions about this Agreement,&nbsp;please contact us.</p>
<p>App: &nbsp;www.monkeyjunior.com</p>
<p><strong style="font-size: 20px; color: black;">Arbitration</strong><br /> For any disputes or discrepancies you may have with Monkey Junior, you agree to first contact us and attempt to resolve the dispute with us informally. Any controversies or disputes arising out of or relating to this Agreement shall be resolved by binding arbitration in accordance with the then-current Commercial Arbitration Rules of the Vietnam International Arbitration Centre. The parties shall select a mutually acceptable arbitrator knowledgeable about issues relating to the subject matter of this Agreement. In the event the parties are unable to agree to such a selection, each party will select an arbitrator and the two arbitrators in turn shall select a third arbitrator, all three of whom shall preside jointly over the matter. The arbitrator shall take place at a location that is reasonably centrally located between the parties, or otherwise mutually agreed upon by the parties.</p>
<p>All documents, materials, and information in the possession of each party that are in any way relevant to the dispute shall be made available to the other party for review and copy no later than 30 days after the notice of arbitration is served.</p>
<p>The arbitrator(s) shall not have the authority to modify any provision of this Agreement or to award punitive damages. The arbitrator(s) shall have the power to issue mandatory orders and restraint orders in connection with the arbitration. The decision rendered by the arbitrator(s) shall be final and binding on the parties, and judgment may be entered in conformity with the decision in any court having jurisdiction. The agreement to arbitration shall be specifically enforceable under the prevailing arbitration law. During the continuance of any arbitration proceeding, the parties shall continue to perform their respective obligations under this Agreement.</p>
<p><strong style="font-size: 20px; color: black;">Copyright and trademark notices</strong></p>
<p>All contents of the www.monkeyjunior.com App are Copyright &copy; 2014 Monkey Junior and/or its suppliers, affiliates and partners. All rights reserved.</p>
<p><em><u>Disclaimer:</u></em> The images, products, services and all included content are provided on an "as is" basis without warranty of any kind, whether express or implied and shall remain under Monkey Junior possession unless agreed upon by Monkey Junior and user/client.</p>
<p>MONKEY JUNIOR SPECIFICALLY DISCLAIMS ANY AND ALL WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.</p>
<p>Monkey Junior takes no responsibility and assumes no liability for any User Content that you or any other user or third party posts or transmits using our images, products or services. You understand and agree that you may be exposed to User Content that is inaccurate, objectionable, inappropriate for children, or otherwise unsuited to your purpose.</p>
<p><strong style="font-size: 20px; color: black;">Trademarks</strong><br /> Monkey Junior&trade; and www.monkeyjunior.com&trade; is registered trademark of Early Start Co. Limited. The names of actual companies and products mentioned herein may be the trademarks of their respective owners.</p>
<p><strong style="font-size: 20px; color: black;">No Waiver.</strong><br /> No waiver of any term of these Terms shall be deemed a further continuing waiver of such term or any term, and Monkey Junior&rsquo;s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision <br /> <br /> <strong style="font-size: 20px; color: black;">Notices and procedure for making claims of copyright infringement<br /> </strong>Pursuant notifications of claimed copyright infringements should be sent to Service Provider's Designated Agent. ALL INQUIRIES NOT RELEVANT TO THE ABOVE PROCEDURE WILL RECEIVE NORESPONSE. <br /> <br /> This Agreement was last modified on October 15, 2014.</p>
</div>